name: Java CI

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      - name: General information
        run: |
          java --version
          d8 --version
      - name: Build mod artifact
        run: |
          chmod +x gradlew
          ./gradlew jar dex
      - name: Upload built mod artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModTemplate (zipped)
          path: build/libs/ModTemplate.jar
